config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root "controller#action"
  root 'flats#index'
  get '/flats/:id', to: 'flats#show', as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'open-uri'

class FlatsController < ApplicationController
  before_action :set_flats
  def index; end

  def show
    @flat = @flats.find { |flat| flat['id'] == params[:id].to_i }
  end

  private

  def set_flats
    url = 'https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json'
    @flats = JSON.parse(URI.open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container my-4">
  <h1>Flats</h1>

  <div class="row">
    <% @flats.each do |flat| %>

      <%= link_to flat_path(flat['id']), class: 'text-decoration-none text-dark col-4' do %>
        <div class="">
          <div class="me-3 mb-3 shadow">
            <img src="<%= flat['imageUrl'] %>" alt="" class="w-100">
            <div class="p-3">
              <%= flat['name'] %>
            </div>
          </div>
        </div>
      <% end %>
      
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container my-4 p-4 shadow">
  <%= link_to 'Back', root_path, class: 'btn btn-primary' %>
  <h1><%= @flat['name'] %></h1>

  <img src="<%= @flat['imageUrl'] %>" class="w-100" alt="">


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Static Airbnb Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>